/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jhindin_jni1_Jni1Wrapper */

#ifndef _Included_com_example_jhindin_jni1_Jni1Wrapper
#define _Included_com_example_jhindin_jni1_Jni1Wrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jhindin_jni1_Jni1Wrapper
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_jhindin_jni1_Jni1Wrapper_getString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
